package com.EdOops.constructors;

public class A {
    String name;
    int id;
    int age;
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getId() {
        return this.id;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getAge() {
        return this.age;
    }
    public A(){
        //  A() koi normal method nahi hai, It is a Constructor
//  Here it is a default constructor, ye us class ke values ke liye default values set kar dega.
//  has no parameters
//  It is automatically generated by the compiler.
//  khud se bhi default cons. bana sakte hai inside class then vo vaali default value use hogi.
        this.name = "null";
        this.id = 0;
        this.age = 0;
    }

    public A (String name, int id, int age){
        this.name = name;
        this.id = id;
        this.age = age;
    }
}
